services:
  comments-db:
    extends:
      file: ./apps/comments/docker-compose.yml
      service: comments-db

  payments-db:
    extends:
      file: ./apps/payments/docker-compose.yml
      service: payments-db

  projects-db:
    extends:
      file: ./apps/projects/docker-compose.yml
      service: projects-db

  tasks-db:
    extends:
      file: ./apps/tasks/docker-compose.yml
      service: tasks-db

  users-db:
    extends:
      file: ./apps/users/docker-compose.yml
      service: users-db
