services:
  users-db:
    image: mysql:8.0
    container_name: users-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3300:3306'
    volumes:
      - ./[users-db]-mysql-data:/var/lib/mysql