apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-db
  template:
    metadata:
      labels:
        app: notifications-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: notifications_db
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: notifications-db-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: notifications-db-storage
          persistentVolumeClaim:
            claimName: notifications-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-db-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    app: notifications-db
