apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service-container
        image: maxfrmklmk/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: AT_SECRET
          value: "cc2fb00260754ab7e7daf72ed2eas341d8d2bda82d5a976e495273af19ed41"
        - name: RT_SECRET
          value: "cc2bda820265a976e49527c2bda83af19ed412fb02easid32fb02eas341d8d"
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
      nodeSelector:
        kubernetes.io/arch: arm64

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
