apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service-container
        image: maxfrmklmk/payments:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "payments-db-service"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "payments-db"
        - name: DB_PORT
          value: "3301"
        - name: STRIPE_WEBHOOK_SECRET
          value: "whsec_508bbd54073c11d989a0fe9539c6afcf4994d7a1c363e3e8639a4bfef32fc90e"
        - name: STRIPE_SECRET_KEY
          value: "sk_test_51Q1rQa03Xll5FlFJf62Nus7Dr0bnHdQpjgqhg9qHAN6WpReieIcggOtWXu0IfMlECbWcpm3GfH9uaC7wxxGoKUf6000RMX2dkW"
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
      nodeSelector:
        kubernetes.io/arch: arm64