services:
  comments-db:
    image: mysql:8.0
    container_name: comments-db
    environment:
      MYSQL_DATABASE: comments_db
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
