services:
  tasks-db:
    image: mysql:8.0
    container_name: tasks-db
    environment:
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
    ports:
      - '3303:3306'
    volumes:
      - ./[tasks-db]-mysql-data:/var/lib/mysql