{{- range .Values.databases }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-db-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: 3306
  selector:
    app: {{ .name }}-db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}-db
  labels:
    app: {{ .name }}-db
spec:
  serviceName: "{{ .name }}-db"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}-db
  template:
    metadata:
      labels:
        app: {{ .name }}-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: {{ .name }}-db
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: {{ .name }}-db-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: {{ .name }}-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---

{{- end }}
