services:
  payments-db:
    image: mysql:8.0
    container_name: payments-db
    environment:
      MYSQL_DATABASE: payments_db
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
    ports:
      - '3304:3306'
    volumes:
      - ./[payments-db]-mysql-data:/var/lib/mysql
