services:
  clients-db:
    image: mysql:8.0
    container_name: clients-db
    environment:
      MYSQL_DATABASE: clients_db
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
