name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api:latest -f apps/api/Dockerfile .

      - name: Push API Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api:latest
