name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api
          - notifications
          - payments
          - projects
          - projects-users
          - tasks
          - tasks-users
          - users
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  deploy_to_eks:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_images
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name taskfusion --region eu-north-1

      - name: Update Docker image tags in Helm values.yaml
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          SERVICES: api notifications payments projects projects-users tasks tasks-users users
        run: |
          for service in $SERVICES; do
            sed -i.bak "s|image: .*|image: $DOCKER_USERNAME/$service:$IMAGE_TAG|g" helm-chart/values.yaml
          done

      - name: Deploy Helm chart to EKS
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade --install taskfusion helm-chart/
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          overrule_existing_kubeconfig: 'true'
