name: Build and Push Projects Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Projects Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/projects/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/projects:latest
          platforms: linux/amd64,linux/arm64